# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MvvmRAC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ReactiveObjC'
  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'SDWebImage'
  # Pods for MvvmRAC

end
